import numpy as np
x=np.array([1,2,3,4])
print("original array")
print(x)
print("Test if none  of the elements of the said array is Zero:")
print(np.all(x))
x=np.array([0,1,2,3])
print("original array :")
print(x)
print("Test if none of the elements of the said array is Zero:")
print(np.all(x))